// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGVEbDyMwH9KccuhZjmj8jRlGQtBmS2sM',
    appId: '1:177328761146:web:2d5abe2dc3b4569c8e8803',
    messagingSenderId: '177328761146',
    projectId: 'task3-26a67',
    authDomain: 'task3-26a67.firebaseapp.com',
    storageBucket: 'task3-26a67.appspot.com',
    measurementId: 'G-K7TS3F0C42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30UsY2C1RNAUYPoouDPenJ374wFUoBxs',
    appId: '1:177328761146:android:8a2a85d0de5ef0428e8803',
    messagingSenderId: '177328761146',
    projectId: 'task3-26a67',
    storageBucket: 'task3-26a67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFiSML06V4g4WOLcOwJRbE_olk1RPTuc',
    appId: '1:177328761146:ios:6e0e62be0d01b0458e8803',
    messagingSenderId: '177328761146',
    projectId: 'task3-26a67',
    storageBucket: 'task3-26a67.appspot.com',
    iosBundleId: 'cach.crystal.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFiSML06V4g4WOLcOwJRbE_olk1RPTuc',
    appId: '1:177328761146:ios:6e0e62be0d01b0458e8803',
    messagingSenderId: '177328761146',
    projectId: 'task3-26a67',
    storageBucket: 'task3-26a67.appspot.com',
    iosBundleId: 'cach.crystal.app',
  );
}
